# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from ..db_utils import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 621, 411))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 150, 271, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.timeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.timeButton.setObjectName("timeButton")
        self.gridLayout.addWidget(self.timeButton, 0, 0, 1, 1)
        self.preassureButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.preassureButton.setObjectName("preassureButton")
        self.gridLayout.addWidget(self.preassureButton, 4, 0, 1, 1)
        self.yAmplitudButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.yAmplitudButton.setObjectName("yAmplitudButton")
        self.gridLayout.addWidget(self.yAmplitudButton, 4, 1, 1, 1)
        self.temperatureButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.temperatureButton.setObjectName("temperatureButton")
        self.gridLayout.addWidget(self.temperatureButton, 3, 0, 1, 1)
        self.coButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.coButton.setObjectName("coButton")
        self.gridLayout.addWidget(self.coButton, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.zAmplitudeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.zAmplitudeButton.setObjectName("zAmplitudeButton")
        self.gridLayout_2.addWidget(self.zAmplitudeButton, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rmsButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.rmsButton.setObjectName("rmsButton")
        self.verticalLayout.addWidget(self.rmsButton)
        self.gridLayout.addLayout(self.verticalLayout, 6, 1, 1, 1)
        self.humidityButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.humidityButton.setObjectName("humidityButton")
        self.gridLayout.addWidget(self.humidityButton, 0, 1, 1, 1)
        self.xAmplitudeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.xAmplitudeButton.setObjectName("xAmplitudeButton")
        self.gridLayout.addWidget(self.xAmplitudeButton, 3, 1, 1, 1)
        self.batteryButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.batteryButton.setObjectName("batteryButton")
        self.gridLayout.addWidget(self.batteryButton, 2, 0, 1, 1)
        self.xFrequencyButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.xFrequencyButton.setObjectName("xFrequencyButton")
        self.gridLayout.addWidget(self.xFrequencyButton, 2, 2, 1, 1)
        self.yFrequencyButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.yFrequencyButton.setObjectName("yFrequencyButton")
        self.gridLayout.addWidget(self.yFrequencyButton, 3, 2, 1, 1)
        self.zFrequencyButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.zFrequencyButton.setObjectName("zFrequencyButton")
        self.gridLayout.addWidget(self.zFrequencyButton, 4, 2, 1, 1)
        self.menuLabel = QtWidgets.QLabel(self.page)
        self.menuLabel.setGeometry(QtCore.QRect(290, 120, 31, 16))
        self.menuLabel.setObjectName("menuLabel")
        self.stackedWidget.addWidget(self.page)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.graphicsView_10 = QtWidgets.QGraphicsView(self.page_12)
        self.graphicsView_10.setGeometry(QtCore.QRect(30, 40, 561, 311))
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.backButton = QtWidgets.QPushButton(self.page_12)
        self.backButton.setGeometry(QtCore.QRect(280, 370, 75, 23))
        self.backButton.setObjectName("backButton")
        self.stackedWidget.addWidget(self.page_12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.backButton.clicked.connect(self.goBack)
        self.temperatureButton.clicked.connect(self.goGraph)
        self.timeButton.clicked.connect(self.goGraph)
        self.rmsButton.clicked.connect(self.goGraph)
        self.coButton.clicked.connect(self.goGraph)
        self.xAmplitudeButton.clicked.connect(self.goGraph)
        self.yAmplitudButton.clicked.connect(self.goGraph)
        self.zAmplitudeButton.clicked.connect(self.goGraph)
        self.xFrequencyButton.clicked.connect(self.goGraph)
        self.yFrequencyButton.clicked.connect(self.goGraph)
        self.zFrequencyButton.clicked.connect(self.goGraph)
        self.humidityButton.clicked.connect(self.goGraph)
        self.preassureButton.clicked.connect(self.goGraph)
        self.batteryButton.clicked.connect(self.goGraph)


        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeButton.setText(_translate("MainWindow", "Time"))
        self.preassureButton.setText(_translate("MainWindow", "Pressure"))
        self.yAmplitudButton.setText(_translate("MainWindow", "Y Amplitude"))
        self.temperatureButton.setText(_translate("MainWindow", "Temperature"))
        self.coButton.setText(_translate("MainWindow", "Co"))
        self.zAmplitudeButton.setText(_translate("MainWindow", "Z Amplitude"))
        self.rmsButton.setText(_translate("MainWindow", "RMS"))
        self.humidityButton.setText(_translate("MainWindow", "Humidity"))
        self.xAmplitudeButton.setText(_translate("MainWindow", "X Amplitude"))
        self.batteryButton.setText(_translate("MainWindow", "Battery"))
        self.xFrequencyButton.setText(_translate("MainWindow", "X Fequency"))
        self.yFrequencyButton.setText(_translate("MainWindow", "Y Frequency"))
        self.zFrequencyButton.setText(_translate("MainWindow", "Z Frequency"))
        self.menuLabel.setText(_translate("MainWindow", "Menú"))
        self.backButton.setText(_translate("MainWindow", "Back"))

    def goBack(self):
        self.stackedWidget.setCurrentIndex(0)

    def goGraph(self):
        self.stackedWidget.setCurrentIndex(1)

    def loadGraph(self, type: str):
        match type:
            case "batt":
                times, values = get_batt_history(self.conexion_db)
                self.plot_graph(times, values, "Battery Level")
            case "temp":
                times, values = get_temp_history(self.conexion_db)
                self.plot_graph(times, values, "Temperature")
            case "pres":
                times, values = get_pres_history(self.conexion_db)
                self.plot_graph(times, values, "Pressure")
            case "hum":
                times, values = get_hum_history(self.conexion_db)
                self.plot_graph(times, values, "Humidity")
            case "co":
                times, values = get_co_history(self.conexion_db)
                self.plot_graph(times, values, "CO")
            case "amp_x":
                times, values = get_amp_x_history(self.conexion_db)
                self.plot_graph(times, values, "X Amplitude")
            case "amp_y":
                times, values = get_amp_y_history(self.conexion_db)
                self.plot_graph(times, values, "Y Amplitude")
            case "amp_z":
                times, values = get_amp_z_history(self.conexion_db)
                self.plot_graph(times, values, "Z Amplitude")
            case "freq_x":
                times, values = get_freq_x_history(self.conexion_db)
                self.plot_graph(times, values, "X Frequency")
            case "freq_y":
                times, values = get_freq_y_history(self.conexion_db)
                self.plot_graph(times, values, "Y Frequency")
            case "freq_z":
                times, values = get_freq_z_history(self.conexion_db)
                self.plot_graph(times, values, "Z Frequency")
            case "rms":
                times, values = get_rms_history(self.conexion_db)
                self.plot_graph(times, values, "RMS")

    def plot_graph(self, times, values, title):
        plt.plot(times, values)
        plt.xlabel('Time')
        plt.ylabel('Value')
        plt.title(title)
        plt.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
